// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(robot) {
    var github;
    github = require("githubot")(robot);
    return robot.respond(/merge ([-_\.0-9a-zA-Z]+\/[-_\.0-9a-zA-Z]+)(\/([-_\.a-zA-z0-9\/]+))? into ([-_\.a-zA-z0-9\/]+)$/i, function(msg) {
      var app, base, head;
      app = msg.match[1];
      head = msg.match[3] || "master";
      base = msg.match[4];
      return github.branches(app).merge(head, {
        base: base
      }, function(merge) {
        if (merge.message) {
          return msg.send(merge.message);
        } else {
          return msg.send("Merged the crap out of it");
        }
      });
    });
  };

}).call(this);
